# Generated by Django 4.2 on 2023-04-09 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('objects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('task', models.TextField()),
                ('date', models.DateField()),
                ('comment', models.TextField()),
                ('photo', models.ImageField(upload_to='photos/done/%Y/%m/%d/')),
                ('done', models.BooleanField(default=False)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objects.objecttable')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
