# Generated by Django 4.2 on 2023-04-09 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('administrate_county', models.CharField(max_length=6)),
                ('cod_number', models.CharField(blank=True, max_length=16)),
                ('ind_zone', models.BooleanField(default=False)),
                ('date', models.DateField(auto_now=True)),
                ('area', models.CharField(max_length=100)),
                ('comments', models.TextField()),
                ('rev_count', models.IntegerField()),
                ('type_obj', models.CharField(max_length=30)),
                ('state_obj', models.CharField(max_length=100)),
                ('sqr', models.IntegerField()),
                ('own', models.CharField(max_length=100)),
                ('actual_user', models.CharField(max_length=100)),
                ('n_prot', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('check_company', models.CharField(max_length=100)),
                ('law', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ObjectVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='video/%Y/%m/%d/')),
                ('obj', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='object_video', to='objects.objecttable')),
            ],
        ),
        migrations.CreateModel(
            name='ObjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('obj', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='object_image', to='objects.objecttable')),
            ],
        ),
    ]
