# Generated by Django 4.2 on 2023-04-09 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objectvideo',
            name='obj',
        ),
        migrations.AddField(
            model_name='objecttable',
            name='photo',
            field=models.ImageField(default='', upload_to='media/photos/%Y/%m/%d/'),
        ),
        migrations.DeleteModel(
            name='ObjectImage',
        ),
        migrations.DeleteModel(
            name='ObjectVideo',
        ),
    ]
