# Generated by Django 4.2 on 2023-04-09 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0002_remove_objectvideo_obj_objecttable_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objecttable',
            name='photo',
            field=models.ImageField(default='', upload_to='photos/%Y/%m/%d/'),
        ),
    ]
