# Generated by Django 4.2 on 2023-04-09 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0003_alter_objecttable_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objecttable',
            name='photo',
            field=models.ImageField(blank=True, default='', upload_to='photos/%Y/%m/%d/'),
        ),
    ]
